services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: test-repo_app
    volumes:
      - shared:/shared

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: test-repo_web
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - shared:/shared

volumes:
  shared: