apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
      - name: app
        image: tywin812/test-repo-app:latest
        command: ["sh", "-c", "./build/testproj && sleep infinity"]